from pathlib import Path
from typing import Tuple
from src.api.schemas import ChangeRequest
from src.validation.schemas import RevenueValidationReport


DBT_PATCH_TEMPLATE = """-- Generated by Evidence Gate Remediation Engine
-- Compatibility Model Patch for ChangeRequest: {change_id}
-- Source Asset URN: {source_asset}
-- Field Transition: {old_field} ({old_type}) -> {new_field} ({new_type})
-- Validation Result: {validation_result} (Metric Delta: {delta_pct:.2f}%)

{{{{ config(materialized='view') }}}}

SELECT
    order_id,
    order_date,
    customer_id,
    -- Maintain legacy '{old_field}' field for backward compatibility with downstream BI assets
    {old_field} AS {old_field},
    -- Corrected '{new_field}' calculation excluding tax and unfulfilled/refunded orders
    CASE 
        WHEN order_status NOT IN ('refunded', 'cancelled') 
        THEN ({old_field} - COALESCE(tax_amount, 0))
        ELSE 0.00
    END AS {new_field},
    tax_amount,
    discount_amount,
    order_status,
    updated_at
FROM {{{{ ref('stg_order_details') }}}};
"""


MIGRATION_TEST_TEMPLATE = '''"""
Generated by Evidence Gate Remediation Engine
Migration Test Suite for {new_field} transition from {old_field}.
Source Asset: {source_asset}
Change ID: {change_id}
"""
import pytest
import duckdb


@pytest.fixture
def migration_test_db():
    conn = duckdb.connect(database=":memory:")
    conn.execute("""
        CREATE TABLE order_details (
            order_id INT,
            {old_field} DECIMAL(10, 2),
            tax_amount DECIMAL(10, 2),
            discount_amount DECIMAL(10, 2),
            order_status VARCHAR
        );
        INSERT INTO order_details VALUES
            (1, 100.00, 7.00, 0.00, 'shipped'),
            (2, 50.00, 3.50, 0.00, 'refunded'),
            (3, 200.00, 14.00, 5.00, 'delivered'),
            (4, 75.00, 5.00, 0.00, 'cancelled');
    """)
    return conn


def test_{new_field}_calculation(migration_test_db):
    """Asserts that {new_field} excludes tax and refunded/cancelled status orders."""
    query = """
    SELECT 
        order_id,
        {old_field},
        CASE 
            WHEN order_status NOT IN ('refunded', 'cancelled') 
            THEN ({old_field} - tax_amount) 
            ELSE 0 
        END AS {new_field}
    FROM order_details
    """
    results = {{row[0]: float(row[2]) for row in migration_test_db.execute(query).fetchall()}}
    
    assert results[1] == 93.00   # Shipped order (100 - 7 tax)
    assert results[2] == 0.00    # Refunded order
    assert results[3] == 186.00  # Delivered order (200 - 14 tax)
    assert results[4] == 0.00    # Cancelled order


def test_{new_field}_bounds_and_non_negative(migration_test_db):
    """Asserts {new_field} never exceeds gross {old_field} and is non-negative."""
    query = """
    SELECT 
        order_id,
        {old_field},
        CASE 
            WHEN order_status NOT IN ('refunded', 'cancelled') 
            THEN ({old_field} - tax_amount) 
            ELSE 0 
        END AS {new_field}
    FROM order_details
    """
    for row in migration_test_db.execute(query).fetchall():
        old_val = float(row[1])
        new_val = float(row[2])
        assert new_val >= 0.0, f"{new_field} {{new_val}} cannot be negative"
        assert new_val <= old_val, f"{new_field} {{new_val}} cannot exceed gross {old_field} {{old_val}}"
'''


def generate_remediation_artifacts(
    change_request: ChangeRequest,
    validation_report: RevenueValidationReport,
    output_dir: Path = Path("examples"),
) -> Tuple[Path, Path]:
    """
    Generates dbt-compatible compatibility patch SQL file and migration test Python file.
    Saves both files into the specified output directory (default: examples/).
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    patch_sql_content = DBT_PATCH_TEMPLATE.format(
        change_id=change_request.change_id,
        source_asset=change_request.source_asset,
        old_field=change_request.old_field,
        new_field=change_request.new_field,
        old_type=change_request.old_type,
        new_type=change_request.new_type,
        validation_result=validation_report.result,
        delta_pct=validation_report.delta_pct,
    )
    
    migration_test_content = MIGRATION_TEST_TEMPLATE.format(
        change_id=change_request.change_id,
        source_asset=change_request.source_asset,
        old_field=change_request.old_field,
        new_field=change_request.new_field,
    )

    patch_path = output_dir / "recognized_revenue_patch.sql"
    test_path = output_dir / "test_recognized_revenue_migration.py"

    with open(patch_path, "w", encoding="utf-8") as f:
        f.write(patch_sql_content.strip() + "\n")

    with open(test_path, "w", encoding="utf-8") as f:
        f.write(migration_test_content.strip() + "\n")

    return patch_path, test_path
