-- Generated by Evidence Gate Remediation Engine
-- Compatibility Model Patch for ChangeRequest: cr-net-revenue-001
-- Source Asset URN: urn:li:dataset:(urn:li:dataPlatform:snowflake,b2fd91.order_entry_db.analytics.order_details,PROD)
-- Field Transition: order_total (decimal) -> recognized_revenue (decimal)
-- Validation Result: failed (Metric Delta: 13.16%)

{{ config(materialized='view') }}

SELECT
    order_id,
    order_date,
    customer_id,
    -- Maintain legacy 'order_total' field for backward compatibility with downstream BI assets
    order_total AS order_total,
    -- Corrected 'recognized_revenue' calculation excluding tax and unfulfilled/refunded orders
    CASE 
        WHEN order_status NOT IN ('refunded', 'cancelled') 
        THEN (order_total - COALESCE(tax_amount, 0))
        ELSE 0.00
    END AS recognized_revenue,
    tax_amount,
    discount_amount,
    order_status,
    updated_at
FROM {{ ref('stg_order_details') }};
