"""
Generated by Evidence Gate Remediation Engine
Migration Test Suite for recognized_revenue transition from order_total.
Source Asset: urn:li:dataset:(urn:li:dataPlatform:snowflake,b2fd91.order_entry_db.analytics.order_details,PROD)
Change ID: cr-net-revenue-001
"""
import pytest
import duckdb


@pytest.fixture
def migration_test_db():
    conn = duckdb.connect(database=":memory:")
    conn.execute("""
        CREATE TABLE order_details (
            order_id INT,
            order_total DECIMAL(10, 2),
            tax_amount DECIMAL(10, 2),
            discount_amount DECIMAL(10, 2),
            order_status VARCHAR
        );
        INSERT INTO order_details VALUES
            (1, 100.00, 7.00, 0.00, 'shipped'),
            (2, 50.00, 3.50, 0.00, 'refunded'),
            (3, 200.00, 14.00, 5.00, 'delivered'),
            (4, 75.00, 5.00, 0.00, 'cancelled');
    """)
    return conn


def test_recognized_revenue_calculation(migration_test_db):
    """Asserts that recognized_revenue excludes tax and refunded/cancelled status orders."""
    query = """
    SELECT 
        order_id,
        order_total,
        CASE 
            WHEN order_status NOT IN ('refunded', 'cancelled') 
            THEN (order_total - tax_amount) 
            ELSE 0 
        END AS recognized_revenue
    FROM order_details
    """
    results = {row[0]: float(row[2]) for row in migration_test_db.execute(query).fetchall()}
    
    assert results[1] == 93.00   # Shipped order (100 - 7 tax)
    assert results[2] == 0.00    # Refunded order
    assert results[3] == 186.00  # Delivered order (200 - 14 tax)
    assert results[4] == 0.00    # Cancelled order


def test_recognized_revenue_bounds_and_non_negative(migration_test_db):
    """Asserts recognized_revenue never exceeds gross order_total and is non-negative."""
    query = """
    SELECT 
        order_id,
        order_total,
        CASE 
            WHEN order_status NOT IN ('refunded', 'cancelled') 
            THEN (order_total - tax_amount) 
            ELSE 0 
        END AS recognized_revenue
    FROM order_details
    """
    for row in migration_test_db.execute(query).fetchall():
        old_val = float(row[1])
        new_val = float(row[2])
        assert new_val >= 0.0, f"recognized_revenue {new_val} cannot be negative"
        assert new_val <= old_val, f"recognized_revenue {new_val} cannot exceed gross order_total {old_val}"
